# Generated by Django 3.2.3 on 2021-12-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200)),
                ('Password', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
