# Generated by Django 3.2.3 on 2021-12-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminu',
            name='std_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
