# Generated by Django 3.2.3 on 2021-12-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_quesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModel',
            new_name='Ques',
        ),
    ]
