# Generated by Django 3.2.3 on 2021-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_rename_quesmodel_ques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_question', models.CharField(max_length=200, null=True)),
                ('ap_op1', models.CharField(max_length=200, null=True)),
                ('ap_op2', models.CharField(max_length=200, null=True)),
                ('ap_op3', models.CharField(max_length=200, null=True)),
                ('ap_op4', models.CharField(max_length=200, null=True)),
                ('ap_ans', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
