# Generated by Django 3.2.3 on 2021-12-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_rename_percentage_result_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(),
        ),
    ]
