# Generated by Django 3.2.3 on 2021-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20211229_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
