# Generated by Django 3.2.3 on 2021-12-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_alter_result_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GKresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gk_score', models.IntegerField(default=0)),
                ('gk_percent', models.IntegerField(default=0)),
                ('gk_correct', models.IntegerField(default=0)),
                ('gk_wrong', models.IntegerField(default=0)),
                ('gk_total', models.IntegerField(default=0)),
                ('GK_idD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.adminu')),
            ],
        ),
    ]
