# Generated by Django 3.2.3 on 2021-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0014_gkresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gkresult',
            name='gk_date',
            field=models.CharField(default='', max_length=300),
        ),
    ]
