# Generated by Django 3.2.3 on 2021-12-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_gkresult_gk_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminu',
            old_name='Password',
            new_name='Phone_number',
        ),
        migrations.AddField(
            model_name='adminu',
            name='Course',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='adminu',
            name='userimage',
            field=models.ImageField(blank=True, null=True, upload_to='userimage'),
        ),
    ]
