# Generated by Django 3.2.3 on 2021-12-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0017_result_ap_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminu',
            name='mesg',
            field=models.CharField(default='', max_length=500),
        ),
    ]
