# Generated by Django 3.2.3 on 2021-12-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0018_adminu_mesg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminu',
            name='mesg',
        ),
    ]
