# Generated by Django 3.2.3 on 2022-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0020_gkresult_gk_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminu',
            name='logintime',
            field=models.CharField(default='', max_length=300),
        ),
    ]
